[package]
edition.workspace = true
license.workspace = true
name = "codex-utils-privacy-filter"
version.workspace = true

[lints]
workspace = true

[dependencies]
codex-protocol = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lib]
doctest = false
